name: travel_plane
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # Base
  cupertino_icons: ^1.0.3
  im_stepper: ^1.0.1+1
  flutter_svg: ^1.1.6
  nb_utils: ^4.4.8
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.1.0
  animated_splash_screen: ^1.3.0
  date_time_picker: 2.1.0
  sliding_up_panel: ^2.0.0+1


  geocoding: ^2.0.0

  #Altharher Store
  cached_network_image: ^3.1.0


# Dev Dependencies 
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0

  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "images/grocery/grocery_ic_logo.png"
  adaptive_icon_background : "#00c97b"

flutter:

  uses-material-design: true

  assets:
   - images/
   - images/icons/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #